name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  token:  # id of input
    description: 'Api token, get it from knowledgemarker.com'
    required: true
    default: 'notspecified'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node20'
  main: 'index.js'